ext {
  artifactId = 'selenide-junit4'
}

dependencies {
  api project(":statics")
  testImplementation rootProject.project(':statics').sourceSets.test.output
  testImplementation rootProject.project(':modules:core').sourceSets.test.output

  api "junit:junit:4.13.2"
  testImplementation "junit:junit:4.13.2"
}

configurations {
  testImplementation.exclude group: "org.junit.platform"
}

tasks.withType(Test).configureEach {
  useJUnit()
}

// JUnit4 tests cannot have JUnit5 tag "smoke", and `useJUnit()` above overrides the tag filter of smoke tasks
tasks.matching { it.name.endsWith('_smoke') }.configureEach {
  enabled = false
}

apply from: rootProject.file('gradle/publish-module.gradle')
