apply plugin: 'java-base'

subprojects {
  configurations {
    javadocClasspathElements {
      canBeConsumed = true
      canBeResolved = false
      extendsFrom(configurations.compileClasspath)
    }
  }
}

repositories {
  mavenCentral()
  maven {
    name = 'Central Portal Snapshots'
    url = 'https://central.sonatype.com/repository/maven-snapshots/'
    mavenContent {
      snapshotsOnly()
    }
    content {
      includeGroup("org.seleniumhq.selenium")
    }
  }
}

configurations {
  javadocForSiteClasspath
}

dependencies {
  subprojects.each { subproject ->
    javadocForSiteClasspath project(path: subproject.path, configuration: 'javadocClasspathElements')
  }
}

tasks.register('javadocForSite', Javadoc) {
  source = subprojects.sourceSets.main.allJava
  destinationDir = file(project.layout.buildDirectory.dir("javadoc-for-site"))
  classpath = configurations.javadocForSiteClasspath

  def javadocStylesheet = file('gradle/javadoc-style.css')
  inputs.file(javadocStylesheet).withPropertyName('javadocStylesheet')
  options.addStringOption('-add-stylesheet', javadocStylesheet.absolutePath)
}
