package com.codeborne.selenide;

import org.jspecify.annotations.Nullable;
import org.openqa.selenium.Cookie;
import org.openqa.selenium.json.Json;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static java.nio.charset.StandardCharsets.UTF_8;
import static org.openqa.selenium.json.Json.MAP_TYPE;

/**
 * State of a browser for one origin: cookies, localStorage and sessionStorage.
 *
 * <pre>{@code
 * BrowserState state = webdriver().getBrowserState();
 * String json = state.toJson();
 * ...
 * webdriver().restoreBrowserState(BrowserState.fromJson(json));
 * }</pre>
 *
 * @see BrowserSession#getBrowserState()
 * @see BrowserSession#saveBrowserState(Path)
 * @see BrowserSession#restoreBrowserState(BrowserState)
 * @see OpenOptions#withBrowserState(Path)
 * @since 7.19.0
 */
public record BrowserState(String origin, List<Cookie> cookies,
                           Map<String, String> localStorage, Map<String, String> sessionStorage) {
  private static final Json json = new Json();

  public BrowserState {
    cookies = List.copyOf(cookies);
    localStorage = Map.copyOf(localStorage);
    sessionStorage = Map.copyOf(sessionStorage);
  }

  /**
   * Read browser state from a file (in JSON format), e.g. previously saved by {@link BrowserSession#saveBrowserState(Path)}
   */
  public static BrowserState fromFile(String file) {
    return fromFile(Path.of(file));
  }

  /**
   * Read browser state from a file (in JSON format), e.g. previously saved by {@link BrowserSession#saveBrowserState(Path)}
   */
  public static BrowserState fromFile(Path file) {
    return fromJson(readFile(file));
  }

  /**
   * Browser state as JSON string (e.g. previously generated by {@link #toJson()})
   */
  @SuppressWarnings("unchecked")
  public static BrowserState fromJson(String jsonText) {
    Map<String, Object> map = json.toType(jsonText, MAP_TYPE);
    List<Map<String, Object>> cookies = (List<Map<String, Object>>) map.getOrDefault("cookies", List.of());
    return new BrowserState(
      requireOrigin((String) map.get("origin")),
      cookies.stream().map(BrowserState::cookieFromMap).toList(),
      (Map<String, String>) map.getOrDefault("localStorage", Map.of()),
      (Map<String, String>) map.getOrDefault("sessionStorage", Map.of())
    );
  }

  /**
   * NB! Error message doesn't include the JSON: it contains credentials.
   */
  private static String requireOrigin(@Nullable String origin) {
    if (origin == null) {
      throw new IllegalArgumentException("Missing \"origin\" in browser state");
    }
    return origin;
  }

  public String toJson() {
    Map<String, Object> result = new LinkedHashMap<>();
    result.put("origin", origin);
    result.put("cookies", cookies.stream().map(BrowserState::cookieToMap).toList());
    result.put("localStorage", localStorage);
    result.put("sessionStorage", sessionStorage);
    return json.toJson(result);
  }

  /**
   * Cookie and storage values are not included: they are credentials.
   */
  @Override
  public String toString() {
    return "BrowserState(%s, cookies: %s, localStorage: %s, sessionStorage: %s)".formatted(
      origin, cookies.stream().map(Cookie::getName).toList(), localStorage.keySet(), sessionStorage.keySet());
  }

  static String readFile(Path file) {
    if (!Files.exists(file)) {
      throw new IllegalArgumentException("Browser state file not found: " + file.toAbsolutePath());
    }
    try {
      return Files.readString(file, UTF_8);
    }
    catch (IOException e) {
      throw new UncheckedIOException("Failed to read browser state from " + file.toAbsolutePath(), e);
    }
  }

  private static Map<String, Object> cookieToMap(Cookie cookie) {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("name", cookie.getName());
    map.put("value", cookie.getValue());
    putIfNotNull(map, "domain", cookie.getDomain());
    putIfNotNull(map, "path", cookie.getPath());
    if (cookie.getExpiry() != null) {
      map.put("expiry", cookie.getExpiry().getTime() / 1000);
    }
    map.put("secure", cookie.isSecure());
    map.put("httpOnly", cookie.isHttpOnly());
    putIfNotNull(map, "sameSite", cookie.getSameSite());
    return map;
  }

  private static void putIfNotNull(Map<String, Object> map, String key, @Nullable Object value) {
    if (value != null) {
      map.put(key, value);
    }
  }

  private static Cookie cookieFromMap(Map<String, Object> map) {
    Cookie.Builder builder = new Cookie.Builder((String) map.get("name"), (String) map.get("value"))
      .domain((String) map.get("domain"))
      .path((String) map.get("path"))
      .isSecure(Boolean.TRUE.equals(map.get("secure")))
      .isHttpOnly(Boolean.TRUE.equals(map.get("httpOnly")))
      .sameSite((String) map.get("sameSite"));
    if (map.get("expiry") instanceof Number expiry) {
      builder.expiresOn(new Date(expiry.longValue() * 1000));
    }
    return builder.build();
  }
}
